AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a CMK in KMS and grants access to other accounts
Parameters:
  DevAccount:
    Description: AWS AccountNumber for dev
    Type: Number
  ProjectName:
    Description: Name of the Build Project
    Type: String
    Default: SampleBuildProject
  Environment:
    Description: Name of the Environment, Kindly Follow the standards [Ex.]- Live - Qc - Dev
    Type: String
  CodeBuildCondition:
    Description: Conditionally adds the access required by code build project role
    Type: String
    Default: false
Conditions:
  AddCodeBuildResource: !Equals [ !Ref CodeBuildCondition, true ]
Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Used by Assumed Roles in Dev/Test/Prod accounts to Encrypt/Decrypt code
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Ref AWS::StackName
        Statement:
          -
            Sid: Allows admin of the key
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
          -
            Sid: Allow use of the key for CryptoGraphy Lambda
            Effect: Allow
            Principal:
              AWS:
                #- !Sub arn:aws:iam::${ProductionAccount}:root
                - !Sub arn:aws:iam::${DevAccount}:root
                - !Sub arn:aws:iam::${AWS::AccountId}:root
                - !If
                #The following Role will not be added to the principals untill build project got created with its build role to be added here.
                  - AddCodeBuildResource
                #This role will be assumed by AWS CodeBuild to decrypt artifacts in the S3 bucket. 
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/${Environment}-${ProjectName}-CodeBuildRole"
                  - !Ref AWS::NoValue
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/codepipeline-crossaccounts
      TargetKeyId: !Ref KMSKey
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: codepipeline-artifact-store-04
    DeletionPolicy: Retain

Outputs:
  CMK:
    Value: !GetAtt [KMSKey,Arn]
  ArtifactBucket:
    Value: !Ref ArtifactBucket

